######################## default configuration ####################
disableHugoGeneratorInject = true
baseURL = "https://digitalamico.com"
title = "AMICO DIGITAL - рівнеміри та вимірювальні системи"
theme = "enov-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "enov" # get your shortname form here : https://disqus.com
defaultContentLanguage = "ua"
# disable language
disableLanguages = ["en"] # desable language from here
[outputs]
home = ["HTML", "RSS", "JSON"]


######################### Plugins #############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/aos/aos.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/aos/aos.js"

############################## navigation ###############################

#################### default parameters ################################
[params]
logo = "images/logo.svg"
# top header
top_header = true
# Meta data
keywords = "АМІКО Діджитал, рівнемір, рівнеміри, системи обліку рідин, АМИКО Диджитал, уровнемер, уровнемеры, системы учета"
description = "AMICO Digital розроблює та виготовляє датчики рівня та інше обладнання і програмне забезпечення для інтеграції у системи автоматичного керування технологічними процесами."
author = "Ievgen Gudyma"
# contact info
address = "Україна, м.Миколаїв, вул. Спаська, будинок 1/7"
phone = "+38(097)979 83 20"
# contact form action
contact_form_action = "https://formspree.io/f/xoqydkap"
# Google Analitycs
google_analitycs_id = "G-VGD15TRLZ4" # your id
# search
search = false
# bootstrap css
bootstrap = "/plugins/bootstrap/bootstrap.min.css"

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = true
label = "Замовити"
link = "contact"

######################### Clients logo ################################
[[params.clients_logo]]
logo = "images/about/key-vision1.png"

[[params.clients_logo]]
logo = "images/about/key-vision2.png"

[[params.clients_logo]]
logo = "images/about/key-vision3.png"

[[params.clients_logo]]
logo = "images/about/key-vision4.png"

[[params.clients_logo]]
logo = "images/about/key-vision3.png"

[[params.clients_logo]]
logo = "images/about/key-vision5.png"

[[params.clients_logo]]
logo = "images/about/key-vision2.png"

[[params.clients_logo]]
logo = "images/about/key-vision1.png"

#################### social icon ######################################
[[params.social]]
name = "Telegram"
icon = "/images/icons/telegram.svg"
link = "https://telegram.me/AmicoDigital"

[[params.social]]
name = "Viber"
icon = "/images/icons/viber.svg"
link = "viber://contact?number=%2B380979798320"

[[params.social]]
name = "Messenger"
icon = "/images/icons/messenger.svg"
link = "http://m.me/AmicoDigital"

########################### English language ###########################
[Languages.en]
languageName = "En"
languageCode = "en-US"
contentDir = "content/english"
weight = 1
home = ""

# main menu
[[Languages.en.menu.main]]
weight = 2
name = "About us"
URL = "about"
hasChildren = false

[[Languages.en.menu.main]]
weight = 3
name = "Products"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Products"
  name = "Level sensor LPG"
  URL = "level-sensor-lpg"

  [[Languages.en.menu.main]]
  parent = "Products"
  name = "Level sensor for liquids"
  URL = "level-sensor"

  [[Languages.en.menu.main]]
  parent = "Products"
  name = "IS Barrier"
  URL = "is-barrier"

[[Languages.en.menu.main]]
name = "News"
URL = "blog"
weight = 4
  
[[Languages.en.menu.main]]
name = "Contacts"
URL = "contact"
weight = 5

# footer menu
[[Languages.en.menu.footer]]
name = "IS Barrier"
URL = "is-barrier"
weight = 1

[[Languages.en.menu.footer]]
name = "Level sensor for liquids"
URL = "level-sensor"
weight = 2

[[Languages.en.menu.footer]]
name = "Level sensor LPG"
URL = "level-sensor-lpg"
weight = 3

########################### Ukraine language ############################
[Languages.ua]
languageName = "UA"
languageCode = "uk-UA"
contentDir = "content/ukrainian"


# main menu
[[Languages.ua.menu.main]]
weight = 2
name = "Про нас"
URL = "about"
hasChildren = false

[[Languages.ua.menu.main]]
weight = 3
name = "Продукти"
hasChildren = true

  [[Languages.ua.menu.main]]
  parent = "Продукти"
  name = "Рівнемір для газів (LPG)"
  URL = "level-sensor-lpg"

  [[Languages.ua.menu.main]]
  parent = "Продукти"
  name = "Рівнемір для рідин"
  URL = "level-sensor"

  [[Languages.ua.menu.main]]
  parent = "Продукти"
  name = "Бар'єр іскрозахисту"
  URL = "is-barrier"

[[Languages.ua.menu.main]]
name = "Новини"
URL = "blog"
weight = 4
  
[[Languages.ua.menu.main]]
name = "Контакти"
URL = "contact"
weight = 5

# footer menu
[[Languages.ua.menu.footer]]
name = "Бар'єр іскрозахисту"
URL = "is-barrier"
weight = 1

[[Languages.ua.menu.footer]]
name = "Рівнемір для рідин"
URL = "level-sensor"
weight = 2

[[Languages.ua.menu.footer]]
name = "Рівнемір для газів"
URL = "level-sensor-lpg"
weight = 3

########################### Russian language ############################
[Languages.ru]
languageName = "RU"
languageCode = "ru-RU"
contentDir = "content/russian"
title = "AMICO DIGITAL - уровнемеры, измерительные системы"
weight = 1
home = ""

# main menu
[[Languages.ru.menu.main]]
weight = 2
name = "О нас"
URL = "about"
hasChildren = false

[[Languages.ru.menu.main]]
weight = 3
name = "Продукты"
hasChildren = true

  [[Languages.ru.menu.main]]
  parent = "Продукты"
  name = "Уровнемер для газов (LPG)"
  URL = "level-sensor-lpg"

  [[Languages.ru.menu.main]]
  parent = "Продукты"
  name = "Уровнемер для жидкостей"
  URL = "level-sensor"

  [[Languages.ru.menu.main]]
  parent = "Продукты"
  name = "Барьер искрозащиты"
  URL = "is-barrier"

[[Languages.ru.menu.main]]
name = "Новости"
URL = "blog"
weight = 4
  
[[Languages.ru.menu.main]]
name = "Контакты"
URL = "contact"
weight = 5

# footer menu
[[Languages.ru.menu.footer]]
name = "Барьер искрозащиты"
URL = "is-barrier"
weight = 1

[[Languages.ru.menu.footer]]
name = "Уровнемер для жидкостей"
URL = "level-sensor"
weight = 2

[[Languages.ru.menu.footer]]
name = "Уровнемер для газов"
URL = "level-sensor-lpg"
weight = 3